resources:
  - name: workshop_repo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: katcosgrove/devops-101-workshop    # replace with your repository name
      branches:
        include: master

  - name: build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      buildName: svc_build
      buildNumber: 1

  - name: promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

pipelines:
  - name: pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kat101.jfrog.io/docker/my-docker-image # Replace with your Docker image path
          dockerImageTag: ${run_number}
          inputResources:
            - name: workshop_repo
          integrations:
            - name: art

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: art
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_1_docker_build_push